// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package kto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tx struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	BlockNum             uint64   `protobuf:"varint,2,opt,name=BlockNum,proto3" json:"BlockNum,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=To,proto3" json:"To,omitempty"`
	Hash                 string   `protobuf:"bytes,6,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Signature            string   `protobuf:"bytes,7,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Time                 int64    `protobuf:"varint,8,opt,name=Time,proto3" json:"Time,omitempty"`
	Script               string   `protobuf:"bytes,9,opt,name=Script,proto3" json:"Script,omitempty"`
	Fee                  uint64   `protobuf:"varint,10,opt,name=Fee,proto3" json:"Fee,omitempty"`
	Root                 []byte   `protobuf:"bytes,11,opt,name=Root,proto3" json:"Root,omitempty"`
	Tag                  int32    `protobuf:"varint,12,opt,name=Tag,proto3" json:"Tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Tx) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *Tx) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Tx) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Tx) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Tx) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Tx) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Tx) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Tx) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *Tx) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Tx) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Tx) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

type Block struct {
	Height               uint64   `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	PrevBlockHash        string   `protobuf:"bytes,2,opt,name=PrevBlockHash,proto3" json:"PrevBlockHash,omitempty"`
	Txs                  []*Tx    `protobuf:"bytes,3,rep,name=Txs,proto3" json:"Txs,omitempty"`
	Root                 string   `protobuf:"bytes,4,opt,name=Root,proto3" json:"Root,omitempty"`
	Version              uint64   `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Hash                 string   `protobuf:"bytes,7,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Miner                string   `protobuf:"bytes,8,opt,name=Miner,proto3" json:"Miner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *Block) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *Block) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *Block) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

type ReqSignedTransaction struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Time                 int64    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Hash                 []byte   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            []byte   `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignedTransaction) Reset()         { *m = ReqSignedTransaction{} }
func (m *ReqSignedTransaction) String() string { return proto.CompactTextString(m) }
func (*ReqSignedTransaction) ProtoMessage()    {}
func (*ReqSignedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *ReqSignedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignedTransaction.Unmarshal(m, b)
}
func (m *ReqSignedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignedTransaction.Marshal(b, m, deterministic)
}
func (m *ReqSignedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignedTransaction.Merge(m, src)
}
func (m *ReqSignedTransaction) XXX_Size() int {
	return xxx_messageInfo_ReqSignedTransaction.Size(m)
}
func (m *ReqSignedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignedTransaction proto.InternalMessageInfo

func (m *ReqSignedTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqSignedTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqSignedTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqSignedTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ReqSignedTransaction) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ReqSignedTransaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ReqSignedTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type HashMsg struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashMsg) Reset()         { *m = HashMsg{} }
func (m *HashMsg) String() string { return proto.CompactTextString(m) }
func (*HashMsg) ProtoMessage()    {}
func (*HashMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *HashMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashMsg.Unmarshal(m, b)
}
func (m *HashMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashMsg.Marshal(b, m, deterministic)
}
func (m *HashMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashMsg.Merge(m, src)
}
func (m *HashMsg) XXX_Size() int {
	return xxx_messageInfo_HashMsg.Size(m)
}
func (m *HashMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HashMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HashMsg proto.InternalMessageInfo

func (m *HashMsg) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HashMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HashMsg) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ReqTokenTransaction struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Priv                 string   `protobuf:"bytes,5,opt,name=priv,proto3" json:"priv,omitempty"`
	TokenAmount          uint64   `protobuf:"varint,6,opt,name=tokenAmount,proto3" json:"tokenAmount,omitempty"`
	Symbol               string   `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Fee                  uint64   `protobuf:"varint,8,opt,name=fee,proto3" json:"fee,omitempty"`
	Time                 int64    `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`
	Hash                 []byte   `protobuf:"bytes,10,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            []byte   `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTokenTransaction) Reset()         { *m = ReqTokenTransaction{} }
func (m *ReqTokenTransaction) String() string { return proto.CompactTextString(m) }
func (*ReqTokenTransaction) ProtoMessage()    {}
func (*ReqTokenTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *ReqTokenTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTokenTransaction.Unmarshal(m, b)
}
func (m *ReqTokenTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTokenTransaction.Marshal(b, m, deterministic)
}
func (m *ReqTokenTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTokenTransaction.Merge(m, src)
}
func (m *ReqTokenTransaction) XXX_Size() int {
	return xxx_messageInfo_ReqTokenTransaction.Size(m)
}
func (m *ReqTokenTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTokenTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTokenTransaction proto.InternalMessageInfo

func (m *ReqTokenTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqTokenTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqTokenTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqTokenTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ReqTokenTransaction) GetPriv() string {
	if m != nil {
		return m.Priv
	}
	return ""
}

func (m *ReqTokenTransaction) GetTokenAmount() uint64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *ReqTokenTransaction) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqTokenTransaction) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *ReqTokenTransaction) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ReqTokenTransaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ReqTokenTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ReqTransaction struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Priv                 string   `protobuf:"bytes,5,opt,name=priv,proto3" json:"priv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTransaction) Reset()         { *m = ReqTransaction{} }
func (m *ReqTransaction) String() string { return proto.CompactTextString(m) }
func (*ReqTransaction) ProtoMessage()    {}
func (*ReqTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *ReqTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTransaction.Unmarshal(m, b)
}
func (m *ReqTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTransaction.Marshal(b, m, deterministic)
}
func (m *ReqTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTransaction.Merge(m, src)
}
func (m *ReqTransaction) XXX_Size() int {
	return xxx_messageInfo_ReqTransaction.Size(m)
}
func (m *ReqTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTransaction proto.InternalMessageInfo

func (m *ReqTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ReqTransaction) GetPriv() string {
	if m != nil {
		return m.Priv
	}
	return ""
}

type ReqBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBalance) Reset()         { *m = ReqBalance{} }
func (m *ReqBalance) String() string { return proto.CompactTextString(m) }
func (*ReqBalance) ProtoMessage()    {}
func (*ReqBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *ReqBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBalance.Unmarshal(m, b)
}
func (m *ReqBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBalance.Marshal(b, m, deterministic)
}
func (m *ReqBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBalance.Merge(m, src)
}
func (m *ReqBalance) XXX_Size() int {
	return xxx_messageInfo_ReqBalance.Size(m)
}
func (m *ReqBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBalance proto.InternalMessageInfo

func (m *ReqBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ResBalance struct {
	Balnce               uint64   `protobuf:"varint,1,opt,name=balnce,proto3" json:"balnce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResBalance) Reset()         { *m = ResBalance{} }
func (m *ResBalance) String() string { return proto.CompactTextString(m) }
func (*ResBalance) ProtoMessage()    {}
func (*ResBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *ResBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResBalance.Unmarshal(m, b)
}
func (m *ResBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResBalance.Marshal(b, m, deterministic)
}
func (m *ResBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResBalance.Merge(m, src)
}
func (m *ResBalance) XXX_Size() int {
	return xxx_messageInfo_ResBalance.Size(m)
}
func (m *ResBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ResBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ResBalance proto.InternalMessageInfo

func (m *ResBalance) GetBalnce() uint64 {
	if m != nil {
		return m.Balnce
	}
	return 0
}

type ReqTokenBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTokenBalance) Reset()         { *m = ReqTokenBalance{} }
func (m *ReqTokenBalance) String() string { return proto.CompactTextString(m) }
func (*ReqTokenBalance) ProtoMessage()    {}
func (*ReqTokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *ReqTokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTokenBalance.Unmarshal(m, b)
}
func (m *ReqTokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTokenBalance.Marshal(b, m, deterministic)
}
func (m *ReqTokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTokenBalance.Merge(m, src)
}
func (m *ReqTokenBalance) XXX_Size() int {
	return xxx_messageInfo_ReqTokenBalance.Size(m)
}
func (m *ReqTokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTokenBalance proto.InternalMessageInfo

func (m *ReqTokenBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReqTokenBalance) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type RespTokenBalance struct {
	Balnce               uint64   `protobuf:"varint,1,opt,name=balnce,proto3" json:"balnce,omitempty"`
	Demic                uint64   `protobuf:"varint,2,opt,name=demic,proto3" json:"demic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespTokenBalance) Reset()         { *m = RespTokenBalance{} }
func (m *RespTokenBalance) String() string { return proto.CompactTextString(m) }
func (*RespTokenBalance) ProtoMessage()    {}
func (*RespTokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *RespTokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespTokenBalance.Unmarshal(m, b)
}
func (m *RespTokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespTokenBalance.Marshal(b, m, deterministic)
}
func (m *RespTokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespTokenBalance.Merge(m, src)
}
func (m *RespTokenBalance) XXX_Size() int {
	return xxx_messageInfo_RespTokenBalance.Size(m)
}
func (m *RespTokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_RespTokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_RespTokenBalance proto.InternalMessageInfo

func (m *RespTokenBalance) GetBalnce() uint64 {
	if m != nil {
		return m.Balnce
	}
	return 0
}

func (m *RespTokenBalance) GetDemic() uint64 {
	if m != nil {
		return m.Demic
	}
	return 0
}

type ReqNonce struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNonce) Reset()         { *m = ReqNonce{} }
func (m *ReqNonce) String() string { return proto.CompactTextString(m) }
func (*ReqNonce) ProtoMessage()    {}
func (*ReqNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *ReqNonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNonce.Unmarshal(m, b)
}
func (m *ReqNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNonce.Marshal(b, m, deterministic)
}
func (m *ReqNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNonce.Merge(m, src)
}
func (m *ReqNonce) XXX_Size() int {
	return xxx_messageInfo_ReqNonce.Size(m)
}
func (m *ReqNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNonce.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNonce proto.InternalMessageInfo

func (m *ReqNonce) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ResposeNonce struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResposeNonce) Reset()         { *m = ResposeNonce{} }
func (m *ResposeNonce) String() string { return proto.CompactTextString(m) }
func (*ResposeNonce) ProtoMessage()    {}
func (*ResposeNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *ResposeNonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResposeNonce.Unmarshal(m, b)
}
func (m *ResposeNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResposeNonce.Marshal(b, m, deterministic)
}
func (m *ResposeNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResposeNonce.Merge(m, src)
}
func (m *ResposeNonce) XXX_Size() int {
	return xxx_messageInfo_ResposeNonce.Size(m)
}
func (m *ResposeNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_ResposeNonce.DiscardUnknown(m)
}

var xxx_messageInfo_ResposeNonce proto.InternalMessageInfo

func (m *ResposeNonce) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type ReqTxByHash struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTxByHash) Reset()         { *m = ReqTxByHash{} }
func (m *ReqTxByHash) String() string { return proto.CompactTextString(m) }
func (*ReqTxByHash) ProtoMessage()    {}
func (*ReqTxByHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *ReqTxByHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTxByHash.Unmarshal(m, b)
}
func (m *ReqTxByHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTxByHash.Marshal(b, m, deterministic)
}
func (m *ReqTxByHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTxByHash.Merge(m, src)
}
func (m *ReqTxByHash) XXX_Size() int {
	return xxx_messageInfo_ReqTxByHash.Size(m)
}
func (m *ReqTxByHash) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTxByHash.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTxByHash proto.InternalMessageInfo

func (m *ReqTxByHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RespTxByHash struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *Tx      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespTxByHash) Reset()         { *m = RespTxByHash{} }
func (m *RespTxByHash) String() string { return proto.CompactTextString(m) }
func (*RespTxByHash) ProtoMessage()    {}
func (*RespTxByHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *RespTxByHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespTxByHash.Unmarshal(m, b)
}
func (m *RespTxByHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespTxByHash.Marshal(b, m, deterministic)
}
func (m *RespTxByHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespTxByHash.Merge(m, src)
}
func (m *RespTxByHash) XXX_Size() int {
	return xxx_messageInfo_RespTxByHash.Size(m)
}
func (m *RespTxByHash) XXX_DiscardUnknown() {
	xxx_messageInfo_RespTxByHash.DiscardUnknown(m)
}

var xxx_messageInfo_RespTxByHash proto.InternalMessageInfo

func (m *RespTxByHash) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespTxByHash) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RespTxByHash) GetData() *Tx {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReqMaxBlockNumber struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMaxBlockNumber) Reset()         { *m = ReqMaxBlockNumber{} }
func (m *ReqMaxBlockNumber) String() string { return proto.CompactTextString(m) }
func (*ReqMaxBlockNumber) ProtoMessage()    {}
func (*ReqMaxBlockNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *ReqMaxBlockNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMaxBlockNumber.Unmarshal(m, b)
}
func (m *ReqMaxBlockNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMaxBlockNumber.Marshal(b, m, deterministic)
}
func (m *ReqMaxBlockNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMaxBlockNumber.Merge(m, src)
}
func (m *ReqMaxBlockNumber) XXX_Size() int {
	return xxx_messageInfo_ReqMaxBlockNumber.Size(m)
}
func (m *ReqMaxBlockNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMaxBlockNumber.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMaxBlockNumber proto.InternalMessageInfo

type RespMaxBlockNumber struct {
	MaxNumber            uint64   `protobuf:"varint,1,opt,name=maxNumber,proto3" json:"maxNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespMaxBlockNumber) Reset()         { *m = RespMaxBlockNumber{} }
func (m *RespMaxBlockNumber) String() string { return proto.CompactTextString(m) }
func (*RespMaxBlockNumber) ProtoMessage()    {}
func (*RespMaxBlockNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *RespMaxBlockNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespMaxBlockNumber.Unmarshal(m, b)
}
func (m *RespMaxBlockNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespMaxBlockNumber.Marshal(b, m, deterministic)
}
func (m *RespMaxBlockNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespMaxBlockNumber.Merge(m, src)
}
func (m *RespMaxBlockNumber) XXX_Size() int {
	return xxx_messageInfo_RespMaxBlockNumber.Size(m)
}
func (m *RespMaxBlockNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_RespMaxBlockNumber.DiscardUnknown(m)
}

var xxx_messageInfo_RespMaxBlockNumber proto.InternalMessageInfo

func (m *RespMaxBlockNumber) GetMaxNumber() uint64 {
	if m != nil {
		return m.MaxNumber
	}
	return 0
}

type ReqBlockByNumber struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBlockByNumber) Reset()         { *m = ReqBlockByNumber{} }
func (m *ReqBlockByNumber) String() string { return proto.CompactTextString(m) }
func (*ReqBlockByNumber) ProtoMessage()    {}
func (*ReqBlockByNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *ReqBlockByNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBlockByNumber.Unmarshal(m, b)
}
func (m *ReqBlockByNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBlockByNumber.Marshal(b, m, deterministic)
}
func (m *ReqBlockByNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBlockByNumber.Merge(m, src)
}
func (m *ReqBlockByNumber) XXX_Size() int {
	return xxx_messageInfo_ReqBlockByNumber.Size(m)
}
func (m *ReqBlockByNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBlockByNumber.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBlockByNumber proto.InternalMessageInfo

func (m *ReqBlockByNumber) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type RespBlock struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *Block   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespBlock) Reset()         { *m = RespBlock{} }
func (m *RespBlock) String() string { return proto.CompactTextString(m) }
func (*RespBlock) ProtoMessage()    {}
func (*RespBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *RespBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespBlock.Unmarshal(m, b)
}
func (m *RespBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespBlock.Marshal(b, m, deterministic)
}
func (m *RespBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespBlock.Merge(m, src)
}
func (m *RespBlock) XXX_Size() int {
	return xxx_messageInfo_RespBlock.Size(m)
}
func (m *RespBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_RespBlock.DiscardUnknown(m)
}

var xxx_messageInfo_RespBlock proto.InternalMessageInfo

func (m *RespBlock) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespBlock) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RespBlock) GetData() *Block {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReqCreateAddr struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateAddr) Reset()         { *m = ReqCreateAddr{} }
func (m *ReqCreateAddr) String() string { return proto.CompactTextString(m) }
func (*ReqCreateAddr) ProtoMessage()    {}
func (*ReqCreateAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{18}
}

func (m *ReqCreateAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateAddr.Unmarshal(m, b)
}
func (m *ReqCreateAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateAddr.Marshal(b, m, deterministic)
}
func (m *ReqCreateAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateAddr.Merge(m, src)
}
func (m *ReqCreateAddr) XXX_Size() int {
	return xxx_messageInfo_ReqCreateAddr.Size(m)
}
func (m *ReqCreateAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateAddr proto.InternalMessageInfo

type RespCreateAddr struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Privkey              string   `protobuf:"bytes,2,opt,name=privkey,proto3" json:"privkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCreateAddr) Reset()         { *m = RespCreateAddr{} }
func (m *RespCreateAddr) String() string { return proto.CompactTextString(m) }
func (*RespCreateAddr) ProtoMessage()    {}
func (*RespCreateAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{19}
}

func (m *RespCreateAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCreateAddr.Unmarshal(m, b)
}
func (m *RespCreateAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCreateAddr.Marshal(b, m, deterministic)
}
func (m *RespCreateAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCreateAddr.Merge(m, src)
}
func (m *RespCreateAddr) XXX_Size() int {
	return xxx_messageInfo_RespCreateAddr.Size(m)
}
func (m *RespCreateAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCreateAddr.DiscardUnknown(m)
}

var xxx_messageInfo_RespCreateAddr proto.InternalMessageInfo

func (m *RespCreateAddr) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RespCreateAddr) GetPrivkey() string {
	if m != nil {
		return m.Privkey
	}
	return ""
}

type ReqSignedTransactions struct {
	Txs                  []*ReqSignedTransaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ReqSignedTransactions) Reset()         { *m = ReqSignedTransactions{} }
func (m *ReqSignedTransactions) String() string { return proto.CompactTextString(m) }
func (*ReqSignedTransactions) ProtoMessage()    {}
func (*ReqSignedTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{20}
}

func (m *ReqSignedTransactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignedTransactions.Unmarshal(m, b)
}
func (m *ReqSignedTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignedTransactions.Marshal(b, m, deterministic)
}
func (m *ReqSignedTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignedTransactions.Merge(m, src)
}
func (m *ReqSignedTransactions) XXX_Size() int {
	return xxx_messageInfo_ReqSignedTransactions.Size(m)
}
func (m *ReqSignedTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignedTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignedTransactions proto.InternalMessageInfo

func (m *ReqSignedTransactions) GetTxs() []*ReqSignedTransaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type RespSignedTransactions struct {
	HashList             []*HashMsg `protobuf:"bytes,1,rep,name=hashList,proto3" json:"hashList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RespSignedTransactions) Reset()         { *m = RespSignedTransactions{} }
func (m *RespSignedTransactions) String() string { return proto.CompactTextString(m) }
func (*RespSignedTransactions) ProtoMessage()    {}
func (*RespSignedTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{21}
}

func (m *RespSignedTransactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSignedTransactions.Unmarshal(m, b)
}
func (m *RespSignedTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSignedTransactions.Marshal(b, m, deterministic)
}
func (m *RespSignedTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSignedTransactions.Merge(m, src)
}
func (m *RespSignedTransactions) XXX_Size() int {
	return xxx_messageInfo_RespSignedTransactions.Size(m)
}
func (m *RespSignedTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSignedTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_RespSignedTransactions proto.InternalMessageInfo

func (m *RespSignedTransactions) GetHashList() []*HashMsg {
	if m != nil {
		return m.HashList
	}
	return nil
}

type ReqTokenTransactions struct {
	Txs                  []*ReqTokenTransaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ReqTokenTransactions) Reset()         { *m = ReqTokenTransactions{} }
func (m *ReqTokenTransactions) String() string { return proto.CompactTextString(m) }
func (*ReqTokenTransactions) ProtoMessage()    {}
func (*ReqTokenTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{22}
}

func (m *ReqTokenTransactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTokenTransactions.Unmarshal(m, b)
}
func (m *ReqTokenTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTokenTransactions.Marshal(b, m, deterministic)
}
func (m *ReqTokenTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTokenTransactions.Merge(m, src)
}
func (m *ReqTokenTransactions) XXX_Size() int {
	return xxx_messageInfo_ReqTokenTransactions.Size(m)
}
func (m *ReqTokenTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTokenTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTokenTransactions proto.InternalMessageInfo

func (m *ReqTokenTransactions) GetTxs() []*ReqTokenTransaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type ReqTransactions struct {
	Txs                  []*ReqTransaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReqTransactions) Reset()         { *m = ReqTransactions{} }
func (m *ReqTransactions) String() string { return proto.CompactTextString(m) }
func (*ReqTransactions) ProtoMessage()    {}
func (*ReqTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{23}
}

func (m *ReqTransactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTransactions.Unmarshal(m, b)
}
func (m *ReqTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTransactions.Marshal(b, m, deterministic)
}
func (m *ReqTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTransactions.Merge(m, src)
}
func (m *ReqTransactions) XXX_Size() int {
	return xxx_messageInfo_ReqTransactions.Size(m)
}
func (m *ReqTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTransactions proto.InternalMessageInfo

func (m *ReqTransactions) GetTxs() []*ReqTransaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type RespTransactions struct {
	HashList             []*HashMsg `protobuf:"bytes,1,rep,name=hashList,proto3" json:"hashList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RespTransactions) Reset()         { *m = RespTransactions{} }
func (m *RespTransactions) String() string { return proto.CompactTextString(m) }
func (*RespTransactions) ProtoMessage()    {}
func (*RespTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{24}
}

func (m *RespTransactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespTransactions.Unmarshal(m, b)
}
func (m *RespTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespTransactions.Marshal(b, m, deterministic)
}
func (m *RespTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespTransactions.Merge(m, src)
}
func (m *RespTransactions) XXX_Size() int {
	return xxx_messageInfo_RespTransactions.Size(m)
}
func (m *RespTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_RespTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_RespTransactions proto.InternalMessageInfo

func (m *RespTransactions) GetHashList() []*HashMsg {
	if m != nil {
		return m.HashList
	}
	return nil
}

func init() {
	proto.RegisterType((*Tx)(nil), "message.Tx")
	proto.RegisterType((*Block)(nil), "message.block")
	proto.RegisterType((*ReqSignedTransaction)(nil), "message.req_signed_transaction")
	proto.RegisterType((*HashMsg)(nil), "message.hashMsg")
	proto.RegisterType((*ReqTokenTransaction)(nil), "message.req_token_transaction")
	proto.RegisterType((*ReqTransaction)(nil), "message.req_transaction")
	proto.RegisterType((*ReqBalance)(nil), "message.req_balance")
	proto.RegisterType((*ResBalance)(nil), "message.res_balance")
	proto.RegisterType((*ReqTokenBalance)(nil), "message.req_token_balance")
	proto.RegisterType((*RespTokenBalance)(nil), "message.resp_token_balance")
	proto.RegisterType((*ReqNonce)(nil), "message.req_nonce")
	proto.RegisterType((*ResposeNonce)(nil), "message.respose_nonce")
	proto.RegisterType((*ReqTxByHash)(nil), "message.req_tx_by_hash")
	proto.RegisterType((*RespTxByHash)(nil), "message.resp_tx_by_hash")
	proto.RegisterType((*ReqMaxBlockNumber)(nil), "message.req_max_block_number")
	proto.RegisterType((*RespMaxBlockNumber)(nil), "message.resp_max_block_number")
	proto.RegisterType((*ReqBlockByNumber)(nil), "message.req_block_by_number")
	proto.RegisterType((*RespBlock)(nil), "message.resp_block")
	proto.RegisterType((*ReqCreateAddr)(nil), "message.req_create_addr")
	proto.RegisterType((*RespCreateAddr)(nil), "message.resp_create_addr")
	proto.RegisterType((*ReqSignedTransactions)(nil), "message.req_signed_transactions")
	proto.RegisterType((*RespSignedTransactions)(nil), "message.resp_signed_transactions")
	proto.RegisterType((*ReqTokenTransactions)(nil), "message.req_token_transactions")
	proto.RegisterType((*ReqTransactions)(nil), "message.req_transactions")
	proto.RegisterType((*RespTransactions)(nil), "message.resp_transactions")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 1083 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x16, 0x45, 0x1d, 0xa2, 0x91, 0x8f, 0x1b, 0xff, 0x0a, 0xc3, 0x3f, 0x89, 0xd5, 0x45, 0x82,
	0x0a, 0x45, 0x1b, 0xb4, 0x29, 0x7a, 0xd3, 0x8b, 0x02, 0x52, 0x5a, 0xdb, 0x48, 0x6c, 0xa3, 0xa0,
	0x89, 0xf6, 0xae, 0x2a, 0x25, 0xad, 0x65, 0xc2, 0x26, 0xa9, 0x70, 0xd7, 0xa9, 0xf4, 0x06, 0xbd,
	0xeb, 0xab, 0xf4, 0x49, 0xfa, 0x00, 0x7d, 0x9a, 0x62, 0x86, 0x4b, 0x8a, 0x2b, 0xcb, 0x76, 0x5a,
	0xa0, 0xbd, 0xdb, 0x99, 0x9d, 0xfd, 0x66, 0xe6, 0x9b, 0x83, 0x28, 0xd8, 0x8c, 0x84, 0x94, 0xc1,
	0x54, 0xbc, 0x9c, 0xa5, 0x89, 0x4a, 0x58, 0x53, 0x8b, 0xfc, 0xd7, 0x2a, 0x54, 0xfd, 0x39, 0xdb,
	0x83, 0xfa, 0x69, 0x12, 0x8f, 0x85, 0x63, 0x75, 0xad, 0x5e, 0xcd, 0xcb, 0x04, 0xe6, 0xc2, 0x83,
	0xc1, 0x55, 0x32, 0xbe, 0x3c, 0xbd, 0x8e, 0x9c, 0x2a, 0x5d, 0x14, 0x32, 0xeb, 0x40, 0xa3, 0x1f,
	0x25, 0xd7, 0xb1, 0x72, 0x6c, 0xba, 0xd1, 0x12, 0x63, 0x50, 0x3b, 0x48, 0x93, 0xc8, 0xa9, 0x75,
	0xad, 0x5e, 0xcb, 0xa3, 0x33, 0xdb, 0x82, 0xaa, 0x9f, 0x38, 0x75, 0xd2, 0x54, 0xfd, 0x04, 0x6d,
	0x8e, 0x02, 0x79, 0xe1, 0x34, 0x32, 0x1b, 0x3c, 0xb3, 0x27, 0xd0, 0x3a, 0x0b, 0xa7, 0x71, 0xa0,
	0xae, 0x53, 0xe1, 0x34, 0xe9, 0x62, 0xa9, 0xc0, 0x17, 0x7e, 0x18, 0x09, 0xe7, 0x41, 0xd7, 0xea,
	0xd9, 0x1e, 0x9d, 0x31, 0x82, 0xb3, 0x71, 0x1a, 0xce, 0x94, 0xd3, 0x22, 0x73, 0x2d, 0xb1, 0x1d,
	0xb0, 0x0f, 0x84, 0x70, 0x80, 0xc2, 0xc2, 0x23, 0xbe, 0xf6, 0x92, 0x44, 0x39, 0xed, 0xae, 0xd5,
	0xdb, 0xf0, 0xe8, 0x8c, 0x56, 0x7e, 0x30, 0x75, 0x36, 0xba, 0x56, 0xaf, 0xee, 0xe1, 0x91, 0xff,
	0x69, 0x41, 0x7d, 0x84, 0xe9, 0x21, 0xf2, 0x91, 0x08, 0xa7, 0x17, 0x4a, 0xd3, 0xa1, 0x25, 0xf6,
	0x1c, 0x36, 0xbf, 0x4f, 0xc5, 0x7b, 0xe2, 0x80, 0x12, 0xa8, 0x92, 0x63, 0x53, 0xc9, 0x9e, 0x82,
	0xed, 0xcf, 0xa5, 0x63, 0x77, 0xed, 0x5e, 0xfb, 0x55, 0xfb, 0x65, 0x4e, 0xbc, 0x3f, 0xf7, 0x50,
	0x5f, 0x04, 0xa3, 0x09, 0xa2, 0x60, 0x1c, 0x68, 0xfe, 0x20, 0x52, 0x19, 0x26, 0x31, 0xb1, 0x54,
	0xf3, 0x72, 0x11, 0x69, 0xc1, 0x64, 0xa5, 0x0a, 0xa2, 0x19, 0xf1, 0x65, 0x7b, 0x4b, 0x45, 0x41,
	0x64, 0xb3, 0x44, 0xe4, 0x1e, 0xd4, 0x4f, 0xc2, 0x58, 0xa4, 0xc4, 0x55, 0xcb, 0xcb, 0x04, 0xfe,
	0xbb, 0x05, 0x9d, 0x54, 0xbc, 0x1b, 0xca, 0x70, 0x1a, 0x8b, 0xc9, 0x50, 0xa5, 0x41, 0x2c, 0x83,
	0xb1, 0x42, 0x17, 0x0c, 0x6a, 0xe7, 0x58, 0x31, 0x2b, 0x03, 0x39, 0xd7, 0x15, 0x53, 0x89, 0x4e,
	0xaf, 0xaa, 0x12, 0x64, 0x24, 0x30, 0xaa, 0x9d, 0x49, 0xe8, 0x2c, 0xa6, 0xbe, 0xa9, 0x65, 0x7d,
	0x43, 0x02, 0x22, 0x2a, 0xac, 0x56, 0x3d, 0xab, 0x16, 0x9e, 0x51, 0x77, 0x91, 0xd7, 0x7c, 0xc3,
	0xa3, 0x33, 0x26, 0x27, 0x8d, 0x9a, 0x6f, 0x78, 0x4b, 0x05, 0x7f, 0x0b, 0x4d, 0xb4, 0x3a, 0x91,
	0x53, 0x7c, 0x3c, 0x4e, 0x26, 0x59, 0x77, 0xda, 0x1e, 0x9d, 0x91, 0x33, 0x4d, 0xad, 0x8e, 0x33,
	0x17, 0x0b, 0x57, 0x76, 0x96, 0x10, 0x9e, 0xf9, 0x6f, 0x55, 0xf8, 0x1f, 0xe6, 0xaf, 0x92, 0x4b,
	0x11, 0xff, 0xfb, 0xe9, 0xcf, 0xd2, 0xf0, 0xbd, 0x6e, 0x78, 0x3a, 0xb3, 0x2e, 0xb4, 0xc9, 0xb5,
	0x9e, 0x99, 0x06, 0xd9, 0x97, 0x55, 0xe8, 0x43, 0x2e, 0xa2, 0x51, 0x72, 0xa5, 0xab, 0xa9, 0x25,
	0x6c, 0xd4, 0x73, 0x91, 0x75, 0x7e, 0xcd, 0xc3, 0x63, 0x41, 0x6f, 0x6b, 0x0d, 0xbd, 0x70, 0x1b,
	0xbd, 0xed, 0x55, 0x7a, 0x7f, 0x81, 0x6d, 0x22, 0xe4, 0xbf, 0xa6, 0x82, 0x7f, 0x0c, 0x6d, 0x74,
	0x3c, 0x0a, 0xae, 0x02, 0x34, 0x71, 0xa0, 0x19, 0x4c, 0x26, 0xa9, 0x90, 0x52, 0xfb, 0xcd, 0x45,
	0xfe, 0x02, 0x0d, 0x65, 0x61, 0xd8, 0x81, 0xc6, 0x28, 0xb8, 0x5a, 0x2e, 0x29, 0x2d, 0xf1, 0xef,
	0x60, 0x77, 0x59, 0xd9, 0x7b, 0x51, 0x4b, 0x3c, 0x57, 0xcb, 0x3c, 0xf3, 0x01, 0xb0, 0x54, 0xc8,
	0xd9, 0x0a, 0xce, 0x2d, 0x4e, 0x31, 0xdd, 0x89, 0x88, 0xc2, 0xb1, 0xde, 0x8b, 0x99, 0xc0, 0x5f,
	0x40, 0x0b, 0x43, 0xc9, 0x72, 0xbf, 0x2b, 0xb1, 0x4d, 0x74, 0x95, 0x48, 0xa1, 0x4d, 0x0b, 0xf2,
	0xac, 0x12, 0x79, 0xfc, 0x39, 0x6c, 0x51, 0x62, 0xf3, 0xe1, 0x68, 0x31, 0xa4, 0x8a, 0xe6, 0x55,
	0xb6, 0x4a, 0x9d, 0xfd, 0x33, 0xd6, 0x11, 0xe3, 0x36, 0xcc, 0x8a, 0x71, 0xa9, 0xdf, 0x3b, 0x2e,
	0xfb, 0x50, 0x9b, 0x04, 0x2a, 0xa0, 0x7a, 0xae, 0x2c, 0x2c, 0xba, 0xe0, 0x1d, 0xd8, 0xc3, 0x38,
	0xa2, 0x60, 0x3e, 0xa4, 0xfd, 0x38, 0x8c, 0xaf, 0xa3, 0x91, 0x48, 0xf9, 0x57, 0x38, 0x52, 0x72,
	0x76, 0xe3, 0x02, 0x1b, 0x2f, 0x0a, 0xe6, 0xa7, 0x24, 0xe8, 0x94, 0x96, 0x0a, 0xfe, 0x19, 0x3c,
	0xa4, 0xfa, 0xd3, 0x8b, 0xd1, 0x22, 0x7f, 0xd4, 0x81, 0xc6, 0x85, 0xb1, 0x74, 0x33, 0x89, 0xff,
	0x04, 0x40, 0x5e, 0xb2, 0xd5, 0xfc, 0xf7, 0x52, 0xe3, 0x46, 0x6a, 0x5b, 0x45, 0x6a, 0x84, 0xa5,
	0xb3, 0xdb, 0xcd, 0xe6, 0x60, 0x9c, 0x8a, 0x40, 0x89, 0x21, 0x96, 0x88, 0x1f, 0xc0, 0x0e, 0xb9,
	0x2c, 0xe9, 0xee, 0x68, 0x28, 0x07, 0x9a, 0xd8, 0xd7, 0x97, 0x62, 0x91, 0xbb, 0xd7, 0x22, 0x3f,
	0x86, 0x47, 0xeb, 0x77, 0xae, 0x64, 0x5f, 0x80, 0xad, 0xe6, 0x08, 0x85, 0x3f, 0x12, 0xfb, 0x45,
	0x60, 0xeb, 0xcd, 0x3d, 0xb4, 0xe5, 0x47, 0xe0, 0x50, 0x54, 0xeb, 0xe0, 0x3e, 0x85, 0x07, 0x58,
	0xf9, 0xe3, 0x50, 0x2a, 0x8d, 0xb9, 0x53, 0x60, 0xea, 0x25, 0xea, 0x15, 0x16, 0xfc, 0x4d, 0xf6,
	0x5b, 0x70, 0x63, 0x17, 0x4a, 0xf6, 0x79, 0x39, 0xac, 0x67, 0x46, 0x58, 0x37, 0xac, 0xb3, 0xa8,
	0xbe, 0x41, 0xae, 0xde, 0x99, 0x28, 0x9f, 0x94, 0x51, 0x1c, 0x13, 0x65, 0xf5, 0x7d, 0x1f, 0xa7,
	0x17, 0xdb, 0xf7, 0x1f, 0xa7, 0xf3, 0xea, 0x8f, 0x06, 0x34, 0x0f, 0x53, 0x21, 0x94, 0x48, 0xd9,
	0xd7, 0x00, 0x87, 0x42, 0x0d, 0xf4, 0xf4, 0xee, 0x19, 0xbe, 0xf5, 0x4c, 0xbb, 0x65, 0x6d, 0xb1,
	0x5e, 0x78, 0x85, 0x1d, 0xc3, 0xf6, 0xf2, 0xad, 0x8f, 0xe9, 0x32, 0x77, 0x0d, 0x05, 0x39, 0xcc,
	0xff, 0xcb, 0x30, 0x2b, 0x7b, 0x83, 0x57, 0x58, 0x1f, 0x76, 0x0f, 0x85, 0xea, 0x67, 0x4d, 0x42,
	0xdf, 0x53, 0x7d, 0xc5, 0x98, 0x81, 0x47, 0x63, 0xee, 0x76, 0x0c, 0x9c, 0x62, 0x29, 0xf0, 0x0a,
	0x1b, 0x40, 0xfb, 0x50, 0x28, 0x7f, 0x3e, 0x58, 0xd0, 0x2f, 0xfb, 0x23, 0x33, 0x98, 0x62, 0xde,
	0x5d, 0x67, 0x25, 0x92, 0xe2, 0x86, 0x57, 0x98, 0x4f, 0x61, 0x9c, 0x04, 0xf3, 0xfc, 0xcb, 0x0d,
	0x67, 0xed, 0xa9, 0x81, 0xb4, 0x3a, 0xbf, 0xee, 0x33, 0x13, 0xef, 0xc6, 0xe0, 0x57, 0xd8, 0xb7,
	0xb0, 0x89, 0x54, 0xa1, 0x72, 0xb0, 0xc0, 0xcf, 0xc1, 0x27, 0x26, 0xd3, 0xe6, 0x6c, 0xbb, 0x0f,
	0x4d, 0x40, 0xba, 0xe6, 0x15, 0xf6, 0x1a, 0xe0, 0x35, 0x8d, 0x58, 0x9f, 0x26, 0xcc, 0x80, 0x28,
	0xcd, 0x9e, 0xfb, 0xd8, 0x7c, 0x5e, 0x1e, 0xd5, 0x0a, 0x1b, 0x42, 0xe7, 0x4c, 0xc4, 0x93, 0x33,
	0x9a, 0x0a, 0xbf, 0xdc, 0x45, 0xdd, 0x7b, 0xc6, 0x4a, 0xba, 0x1f, 0x99, 0xc0, 0x6b, 0x4c, 0x78,
	0x85, 0xfd, 0x08, 0xdb, 0x25, 0x07, 0xd4, 0x16, 0xfb, 0x77, 0x4f, 0xc6, 0x07, 0x02, 0xbf, 0x85,
	0x1d, 0x04, 0x36, 0x62, 0x7e, 0x7c, 0xdb, 0xb4, 0x48, 0xd7, 0x5d, 0xa9, 0xb2, 0x09, 0xf6, 0x06,
	0x5a, 0x04, 0xf6, 0x61, 0xf1, 0xdd, 0x89, 0x35, 0x6a, 0xd0, 0x9f, 0x84, 0x2f, 0xff, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x5b, 0x73, 0x2e, 0x10, 0x35, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	GetBalance(ctx context.Context, in *ReqBalance, opts ...grpc.CallOption) (*ResBalance, error)
	GetBalanceToken(ctx context.Context, in *ReqTokenBalance, opts ...grpc.CallOption) (*RespTokenBalance, error)
	GetAddressNonceAt(ctx context.Context, in *ReqNonce, opts ...grpc.CallOption) (*ResposeNonce, error)
	GetTxByHash(ctx context.Context, in *ReqTxByHash, opts ...grpc.CallOption) (*RespTxByHash, error)
	GetMaxBlockNumber(ctx context.Context, in *ReqMaxBlockNumber, opts ...grpc.CallOption) (*RespMaxBlockNumber, error)
	GetBlockByNum(ctx context.Context, in *ReqBlockByNumber, opts ...grpc.CallOption) (*RespBlock, error)
	CreateAddr(ctx context.Context, in *ReqCreateAddr, opts ...grpc.CallOption) (*RespCreateAddr, error)
	SendSignedTransactions(ctx context.Context, in *ReqSignedTransactions, opts ...grpc.CallOption) (*RespSignedTransactions, error)
	SendSignedToken(ctx context.Context, in *ReqTokenTransactions, opts ...grpc.CallOption) (*RespSignedTransactions, error)
	SendTransactions(ctx context.Context, in *ReqTransactions, opts ...grpc.CallOption) (*RespTransactions, error)
	SendToken(ctx context.Context, in *ReqTokenTransactions, opts ...grpc.CallOption) (*RespTransactions, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetBalance(ctx context.Context, in *ReqBalance, opts ...grpc.CallOption) (*ResBalance, error) {
	out := new(ResBalance)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetBalanceToken(ctx context.Context, in *ReqTokenBalance, opts ...grpc.CallOption) (*RespTokenBalance, error) {
	out := new(RespTokenBalance)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBalanceToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetAddressNonceAt(ctx context.Context, in *ReqNonce, opts ...grpc.CallOption) (*ResposeNonce, error) {
	out := new(ResposeNonce)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetAddressNonceAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetTxByHash(ctx context.Context, in *ReqTxByHash, opts ...grpc.CallOption) (*RespTxByHash, error) {
	out := new(RespTxByHash)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetTxByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetMaxBlockNumber(ctx context.Context, in *ReqMaxBlockNumber, opts ...grpc.CallOption) (*RespMaxBlockNumber, error) {
	out := new(RespMaxBlockNumber)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetMaxBlockNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetBlockByNum(ctx context.Context, in *ReqBlockByNumber, opts ...grpc.CallOption) (*RespBlock, error) {
	out := new(RespBlock)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBlockByNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CreateAddr(ctx context.Context, in *ReqCreateAddr, opts ...grpc.CallOption) (*RespCreateAddr, error) {
	out := new(RespCreateAddr)
	err := c.cc.Invoke(ctx, "/message.Greeter/CreateAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SendSignedTransactions(ctx context.Context, in *ReqSignedTransactions, opts ...grpc.CallOption) (*RespSignedTransactions, error) {
	out := new(RespSignedTransactions)
	err := c.cc.Invoke(ctx, "/message.Greeter/SendSignedTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SendSignedToken(ctx context.Context, in *ReqTokenTransactions, opts ...grpc.CallOption) (*RespSignedTransactions, error) {
	out := new(RespSignedTransactions)
	err := c.cc.Invoke(ctx, "/message.Greeter/SendSignedToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SendTransactions(ctx context.Context, in *ReqTransactions, opts ...grpc.CallOption) (*RespTransactions, error) {
	out := new(RespTransactions)
	err := c.cc.Invoke(ctx, "/message.Greeter/SendTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SendToken(ctx context.Context, in *ReqTokenTransactions, opts ...grpc.CallOption) (*RespTransactions, error) {
	out := new(RespTransactions)
	err := c.cc.Invoke(ctx, "/message.Greeter/SendToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	GetBalance(context.Context, *ReqBalance) (*ResBalance, error)
	GetBalanceToken(context.Context, *ReqTokenBalance) (*RespTokenBalance, error)
	GetAddressNonceAt(context.Context, *ReqNonce) (*ResposeNonce, error)
	GetTxByHash(context.Context, *ReqTxByHash) (*RespTxByHash, error)
	GetMaxBlockNumber(context.Context, *ReqMaxBlockNumber) (*RespMaxBlockNumber, error)
	GetBlockByNum(context.Context, *ReqBlockByNumber) (*RespBlock, error)
	CreateAddr(context.Context, *ReqCreateAddr) (*RespCreateAddr, error)
	SendSignedTransactions(context.Context, *ReqSignedTransactions) (*RespSignedTransactions, error)
	SendSignedToken(context.Context, *ReqTokenTransactions) (*RespSignedTransactions, error)
	SendTransactions(context.Context, *ReqTransactions) (*RespTransactions, error)
	SendToken(context.Context, *ReqTokenTransactions) (*RespTransactions, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GetBalance(ctx context.Context, req *ReqBalance) (*ResBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (*UnimplementedGreeterServer) GetBalanceToken(ctx context.Context, req *ReqTokenBalance) (*RespTokenBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalanceToken not implemented")
}
func (*UnimplementedGreeterServer) GetAddressNonceAt(ctx context.Context, req *ReqNonce) (*ResposeNonce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressNonceAt not implemented")
}
func (*UnimplementedGreeterServer) GetTxByHash(ctx context.Context, req *ReqTxByHash) (*RespTxByHash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxByHash not implemented")
}
func (*UnimplementedGreeterServer) GetMaxBlockNumber(ctx context.Context, req *ReqMaxBlockNumber) (*RespMaxBlockNumber, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMaxBlockNumber not implemented")
}
func (*UnimplementedGreeterServer) GetBlockByNum(ctx context.Context, req *ReqBlockByNumber) (*RespBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByNum not implemented")
}
func (*UnimplementedGreeterServer) CreateAddr(ctx context.Context, req *ReqCreateAddr) (*RespCreateAddr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddr not implemented")
}
func (*UnimplementedGreeterServer) SendSignedTransactions(ctx context.Context, req *ReqSignedTransactions) (*RespSignedTransactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSignedTransactions not implemented")
}
func (*UnimplementedGreeterServer) SendSignedToken(ctx context.Context, req *ReqTokenTransactions) (*RespSignedTransactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSignedToken not implemented")
}
func (*UnimplementedGreeterServer) SendTransactions(ctx context.Context, req *ReqTransactions) (*RespTransactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransactions not implemented")
}
func (*UnimplementedGreeterServer) SendToken(ctx context.Context, req *ReqTokenTransactions) (*RespTransactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToken not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBalance(ctx, req.(*ReqBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetBalanceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTokenBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBalanceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBalanceToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBalanceToken(ctx, req.(*ReqTokenBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetAddressNonceAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNonce)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetAddressNonceAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetAddressNonceAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetAddressNonceAt(ctx, req.(*ReqNonce))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetTxByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTxByHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetTxByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetTxByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetTxByHash(ctx, req.(*ReqTxByHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetMaxBlockNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMaxBlockNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetMaxBlockNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetMaxBlockNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetMaxBlockNumber(ctx, req.(*ReqMaxBlockNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetBlockByNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBlockByNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBlockByNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBlockByNum(ctx, req.(*ReqBlockByNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CreateAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCreateAddr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CreateAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/CreateAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CreateAddr(ctx, req.(*ReqCreateAddr))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SendSignedTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSignedTransactions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SendSignedTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SendSignedTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SendSignedTransactions(ctx, req.(*ReqSignedTransactions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SendSignedToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTokenTransactions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SendSignedToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SendSignedToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SendSignedToken(ctx, req.(*ReqTokenTransactions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SendTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTransactions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SendTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SendTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SendTransactions(ctx, req.(*ReqTransactions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SendToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTokenTransactions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SendToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SendToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SendToken(ctx, req.(*ReqTokenTransactions))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _Greeter_GetBalance_Handler,
		},
		{
			MethodName: "GetBalanceToken",
			Handler:    _Greeter_GetBalanceToken_Handler,
		},
		{
			MethodName: "GetAddressNonceAt",
			Handler:    _Greeter_GetAddressNonceAt_Handler,
		},
		{
			MethodName: "GetTxByHash",
			Handler:    _Greeter_GetTxByHash_Handler,
		},
		{
			MethodName: "GetMaxBlockNumber",
			Handler:    _Greeter_GetMaxBlockNumber_Handler,
		},
		{
			MethodName: "GetBlockByNum",
			Handler:    _Greeter_GetBlockByNum_Handler,
		},
		{
			MethodName: "CreateAddr",
			Handler:    _Greeter_CreateAddr_Handler,
		},
		{
			MethodName: "SendSignedTransactions",
			Handler:    _Greeter_SendSignedTransactions_Handler,
		},
		{
			MethodName: "SendSignedToken",
			Handler:    _Greeter_SendSignedToken_Handler,
		},
		{
			MethodName: "SendTransactions",
			Handler:    _Greeter_SendTransactions_Handler,
		},
		{
			MethodName: "SendToken",
			Handler:    _Greeter_SendToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
