HttpPort: ":3000"
SecretKey: "dsajflkadsjglafsdj"
LogPath: trs_hash.log
Mysql:
  Dns: root:12345678@tcp(127.0.0.1:3306)/crowd_local?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
Redis:
  Addr: "localhost:6379"
  Password: "123456"
  Db: 5
MiningJob:
  SyncPcb: "0 50 23 * * ?"
  MiningPcb: "0 0 0 * * ?"
